import { useGetBadgeHistoryQuery, useDownloadBadgeMutation } from '@/store/services/api';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Download, History, User, Building2, Calendar, FileText, Loader2 } from 'lucide-react';
import { format } from 'date-fns';
import { toast } from 'sonner';

export function BadgeHistory() {
    const { data: history, isLoading, refetch } = useGetBadgeHistoryQuery();
    const [downloadBadge, { isLoading: isDownloading }] = useDownloadBadgeMutation();

    const handleDownload = async (id: number, userName: string) => {
        try {
            const blob = await downloadBadge(id).unwrap();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `Badge_${userName.replace(/\s+/g, '_')}.pdf`;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);
        } catch (error) {
            console.error('Download failed:', error);
            toast.error('Failed to download badge PDF');
        }
    };

    if (isLoading) {
        return (
            <div className="flex h-[400px] items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
        );
    }

    if (!history || history.length === 0) {
        return (
            <Card className="border-0 shadow-xl overflow-hidden">
                <CardHeader className="bg-slate-50/50 pb-8 border-b">
                    <CardTitle className="font-sans text-xl font-bold">Generation Logs</CardTitle>
                    <CardDescription>Comprehensive history of all badges generated by the system.</CardDescription>
                </CardHeader>
                <CardContent className="min-h-[400px] flex flex-col items-center justify-center p-12">
                    <div className="h-16 w-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
                        <History className="h-8 w-8 text-slate-400" />
                    </div>
                    <h3 className="text-lg font-bold text-slate-900">No logs yet</h3>
                    <p className="text-slate-500 max-w-sm text-center mt-2">
                        When you start generating badges for approved journalists, the records will appear here for tracking and re-download.
                    </p>
                    <Button onClick={() => refetch()} variant="outline" className="mt-6">
                        <Loader2 className={`mr-2 h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
                        Refresh Logs
                    </Button>
                </CardContent>
            </Card>
        );
    }

    return (
        <Card className="border-0 shadow-xl overflow-hidden">
            <CardHeader className="bg-slate-50/50 pb-6 border-b flex flex-row items-center justify-between">
                <div>
                    <CardTitle className="font-sans text-xl font-bold">Generation Logs</CardTitle>
                    <CardDescription>View and download previously generated badges.</CardDescription>
                </div>
                <Button onClick={() => refetch()} variant="outline" size="sm">
                    <History className="mr-2 h-4 w-4" />
                    Refresh
                </Button>
            </CardHeader>
            <CardContent className="p-0">
                <Table>
                    <TableHeader className="bg-slate-50/50">
                        <TableRow>
                            <TableHead className="font-bold">Journalist</TableHead>
                            <TableHead className="font-bold">Organization</TableHead>
                            <TableHead className="font-bold">Config Used</TableHead>
                            <TableHead className="font-bold">Generated At</TableHead>
                            <TableHead className="text-right font-bold w-[150px]">Action</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {history.map((record) => (
                            <TableRow key={record.id} className="hover:bg-slate-50/50 transition-colors">
                                <TableCell>
                                    <div className="flex items-center gap-2">
                                        <div className="h-8 w-8 rounded-full bg-blue-50 flex items-center justify-center">
                                            <User className="h-4 w-4 text-blue-600" />
                                        </div>
                                        <span className="font-medium text-slate-900">{record.application?.user?.fullName || 'N/A'}</span>
                                    </div>
                                </TableCell>
                                <TableCell>
                                    <div className="flex items-center gap-2 text-slate-600">
                                        <Building2 className="h-4 w-4 opacity-50" />
                                        {record.application?.formData?.media_affiliation || record.application?.formData?.organization || 'N/A'}
                                    </div>
                                </TableCell>
                                <TableCell>
                                    <div className="flex items-center gap-2 text-slate-600">
                                        <FileText className="h-4 w-4 opacity-50" />
                                        {record.config?.name || 'Default Template'}
                                    </div>
                                </TableCell>
                                <TableCell>
                                    <div className="flex items-center gap-2 text-slate-600">
                                        <Calendar className="h-4 w-4 opacity-50" />
                                        {format(new Date(record.createdAt), 'MMM dd, yyyy HH:mm')}
                                    </div>
                                </TableCell>
                                <TableCell className="text-right">
                                    <Button
                                        size="sm"
                                        variant="default"
                                        className="bg-blue-600 hover:bg-blue-700 h-9 px-4 gap-2"
                                        onClick={() => handleDownload(record.id, record.application?.user?.fullName || 'Badge')}
                                        disabled={isDownloading || record.status === 'failed'}
                                    >
                                        <Download className="h-4 w-4" />
                                        Download
                                    </Button>
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </CardContent>
        </Card>
    );
}
